# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
#   "iPhone 8",
  "iPhone 8 Plus",      # 5.5inch
  "iPhone 12 Pro Max",  # 6.5inch
#   "iPhone SE",
#   "iPhone X",
#   "iPad Pro (12.9-inch)",
#   "iPad Pro (9.7-inch)",
#   "Apple TV 1080p",
#   "Apple Watch Series 6 - 44mm"
])

#  テスト実行の時に使用する言語一覧
languages(["ja-JP"])

#  スクリーンショットをどこに保存するか
output_directory("./screenshots")

#  スクリーンショット取得時に前回取得した分を破棄するかどうか
clear_previous_screenshots(true)

#  自動実行するテスト(スクリーンショット取得用メソッド)を個別指定可能
only_testing([
  "Shuffle100UITests/FastlaneSnapshot/test_RecitePoemScreenShot",
  "Shuffle100UITests/FastlaneSnapshot/test_IntervalScreenShot",
])

# The name of the scheme which contains the UI Tests
scheme("Shuffle100")

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
