# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rake'
gem 'rspec'
gem 'appium_lib'
gem 'selenium-webdriver'
gem 'slack-notifier'
